In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [31]:
ff_data = pd.read_csv(
    "C:/Users/margo.DESKTOP-T66VM01/Desktop/UBC_Program/522_workflows/forest-fire-area-prediction-group-2/data/raw/forestfires.csv"
)

ff_data["area_log"] = round(np.log(ff_data.area + 1), 3)
seasons = ["NONE"] * len(ff_data)

for x in range(0, len(ff_data)):
    m = ff_data.loc[x, "month"]
    if m in ["dec, jan, feb"]:
        seasons[x] = "winter"
    elif m in ["mar", "apr", "may"]:
        seasons[x] = "spring"
    elif m in ["jun", "jul", "aug"]:
        seasons[x] = "summer"
    elif m in ["sep", "oct", "nov"]:
        seasons[x] = "fall"

ff_data["seasons"] = seasons

train_df, test_df = train_test_split(ff_data, test_size=0.2, random_state=123)

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,area_log,seasons
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,0.000,spring
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,0.000,fall
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,0.000,fall
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,0.000,spring
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,0.000,spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,4,3,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,2.007,summer
513,2,4,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,4.013,summer
514,7,4,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,2.498,summer
515,1,4,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,0.000,summer
516,6,3,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,0.000,fall